### ISSUE TITLE
Add RTLCSS to the registry

### ISSUE THREAD

**Issue by aymanrady** [TrySound/postcss-load-plugins#2]
[RTLCSS](https://github.com/MohammadYounes/rtlcss) is missing from the registry

**Comment by TrySound** [comment]
@aymanrady  You can make PR, I will publish.

**Comment by TrySound** [comment]
@aymanrady And don't forget to star. 20 stars let me be linked in postcss repo.

**Comment by TrySound** [comment]
@aymanrady For now you can use pattern in your project.
```js
{
  pattern: [
    "rtlcss"
  ]
}
```

**Comment by aymanrady** [comment]
@TrySound I am using the pattern option
